#!/bin/bash

########################################################################################
# Este script facilita o processo de reinstalação do grub, caso o MBR seja corrompido,
# mantenha este em seu sistema de arquivos, para auxiliar em caso de emergência e use
# qualquer 'live boot cd' com acesso ao cmd para executa-lo
#
# Para usar, primeiro edite os parâmentros abaixo, de acordo com o seu sistema
# depois entre como root:
# 'sudo su' ou 'sudo -i'
# Logo em seguida rode este script:
# source bootcd-reinstallgrub
#########################################################################################

#########################################################################################
#Parâmetros de configuração:
#########################################################################################

#Define a partição do sistema
#Exemplo: /dev/sda1
proot=/dev/sdXY

#Define o dispositivo onde o grub será instalado
#Exemplo: /dev/sda
gdevice=/dev/sdX

#########################################################################################

begin(){
    mount proot /mnt
    mount --bind /dev /mnt/dev
    mount --bind /dev/pts /mnt/dev/pts
    mount --bind /proc /mnt/proc   
    mount --bind /sys /mnt/sys
    chroot /mnt
    grub-install gdevice
    update-grub
    echo "Tudo pronto, reinicie para testar"
}

if [ $(id -u) != 0 ] 
    then
        echo "Você deve executar este script como super usuário"
        exit
fi

echo "Partição onde o sistema está instalado: "proot
echo "Dispositivo onde o grub será instalado: "gdevice
echo
echo "Para alterar esses valores, edite este script"
echo

while true; do
    read -p "Tem certeza que deseja continuar? S ou N: " sn
        case $sn in
            [Ss]* ) begin;;
            [Nn]* ) exit;;
            * ) echo "Responda S(sim) ou N(não): ";;
        esac
done
